version: 2
jobs:
  build_web_api:
    docker:
      - image: circleci/node:14.16
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - restore_cache:
          name: Restore npm Package Cache
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-master
            - npm-packages-
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          name: Save NPM Packages Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run:
          name: Install AWS CLI
          command: 
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" &&
            unzip awscli-bundle.zip && sudo ./awscli-bundle/install -i /usr/local/aws -b
            /usr/local/bin/aws
      - run:
          name: Install jq
          command: sudo apt-get install jq
      - run:
          name: Copy Environment File
          command: ./scripts/encode_env.sh
      - run:
          name: Build the project
          command: CI=false npm run build
      - run:
          name: Deploy the image
          command: ./scripts/deploy.sh
workflows:
  version: 2
  build_server:
    jobs:
      - build_web_api